packages:
  - "apps/*"
  - "packages/*"


catalog:
 
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^14.1.0

 
  hono: ^4.6.3

  
  typescript: ^5.3.3
  tsup: ^8.5.1

  
  drizzle-orm: ^0.30.10
  zod: ^3.23.8

 
  dotenv: ^16.4.5
